#!/usr/bin/env bash
#starts stop restart script depending on the argument passed
  
   PROGRAM='manage_my_process'
   RELPATH="S{0%/'}/${PROGRAM}"
   PIDFILE="S{PIDFILE:-/var/run/my_process.PID}"

   declare -A MESSAGES=(
      ['start']='started'
      ['stop']='stopped'
      ['restart']='restarted' )
      


